"use client";

import { SnackbarProvider } from "notistack";
import "./globals.scss";
import ThemeCustomization from "@/themes/index";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeCustomization>
          <SnackbarProvider>{children}</SnackbarProvider>
        </ThemeCustomization>
      </body>
    </html>
  );
}
