import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import EventListeners from "@/components/EventListener/EventListener";
import dynamic from "next/dynamic";

const ClientProvider = dynamic(() => import('@/clientProvider/ClientProvider'), { ssr: false })


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
        <Toaster richColors position="bottom-left" />
        <EventListeners />
        {children}
        </ClientProvider>
        </body>
    </html>
  );
}
